# Generated by Django 4.2.8 on 2023-12-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('rental_time', models.IntegerField()),
                ('place_code', models.IntegerField()),
                ('place_name', models.CharField(max_length=100)),
                ('rental_category', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('exercise', models.FloatField()),
                ('carbon', models.FloatField()),
                ('travel_distance', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
