# Generated by Django 4.2.8 on 2024-01-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
